#!/usr/bin/env python3


# imports
import json
import requests
import sys

# args
if (len(sys.argv)<=1):
	print("Usage "+sys.argv[0]+" IP_ADDR ")
	exit()
else:
	ip=sys.argv[1]
	url="http://ipinfo.io/"+str(ip)+"?token=76863d62b05f81"
	bar="----------------------------------------"


# main
def dis(a):
	print("IP Address:-\t\t"+a['ip'])
	if "hostname" in a:
		print("Hostname:-\t\t"+a['hostname'])
	if "loc" in a:
		print("Location:-\t\t"+str(a['loc']))
	if "city" in a:
		print("City:-\t\t\t"+a['city'])
	if "timezone" in a:
		print("Timezone:-\t\t"+a['timezone'])
print(bar)
r=json.loads(requests.get(url).text)
dis(r)
print(bar)
